spring.application.name=SpringBootMVC-5-EcommerceApplication
spring.datasource.url=jdbc:mysql://localhost:3306/10March

spring.datasource.username=root

spring.datasource.password=tiger

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
